### ISSUE TITLE
Typo in config parameter

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/custom_homematic#107]
While working on the documentation I have noticed, that there's a typo for the Bidcos-RF parameters [here](https://github.com/danielperna84/custom_homematic/blob/f62921ef973b06b679781be7e2bde8707208fe12/custom_components/hahm/strings.json#L25). It should be `bidcos` instead of `bidos`.

As I don't know which effect changing this will have for our existing testers, I chose not to fix this yet. Perhaps we should do this once the time has come to migrate the project into the real Home Assistant when everybody has to redo the configuration anyways.

**Comment by SukramJ** [comment]
Good catch. 
That can be fixed now. It's used in the ConfigFlow, but not written to the config entry.
