### ISSUE TITLE
es werden keine geräte gefunden

### ISSUE THREAD

**Issue by elchi007** [danielperna84/custom_homematic#179]
Hallo,

trotz einer Menge Versuche werden einfach keine Geräte gefunden ausser "BidCoS-RF" und "HmIP-RCV-1" und 16 deaktivierter Entitäten. ich habe alle RPC beschränkungen aufgehoben und eine steuerung mit FHEM funktioniert auch. Muss man das AutoDiscover noch aktivieren ? 
Habt ihr noch Ideen ?

Gruß

**Comment by SukramJ** [comment]
Please open a ticket in hahomematic repo as mentioned on the frontpage
