### ISSUE TITLE
(Persistent) Notifications for service messages

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/custom_homematic#32]
The old integration is only showing the number of service messages. It would be nice if the new integration could actually emit (persistent) notifications that are shown in the Home Assistant UI.

**Comment by SukramJ** [comment]
What should be the content of the notification? Any other source than service messages?

Service messages are implemented for BidcosRF, but there is still an [issue](https://github.com/eq-3/occu/issues/54#issuecomment-789532240) with HmIP-RF.
It took me hours to find out that 0001D3C98DD4B6:3 is a default return for HmIP-RF, and not an unreachable device on both of my CCUs.

**Comment by danielperna84** [comment]
> What should be the content of the notification? Any other source than service messages?

I would go with the raw message we get from the CCU. I know those are constants for which the CCU has _nice_ strings, but those then would have to be maintained here as well. In that regard I would argue it makes more sense to use the translations of the HA-component (if available) as they could be localized.  
Following that approach the worst case would be the _cryptic_ message, which users probably still understand what they mean, and if a translation is available, that could be used instead.

I have not yet noticed the HmIP-RF bug. Good to know about this. 👍

**Comment by SukramJ** [comment]
Do we need service messages or should we use events like STICKY_UNREACH, ERROR and CONFIG_PENDING.
UNREACH == True will make devices and their entities unavalable.
CONFIG_PENDING is also covered: if there is a state transition from true -> false the parameter_data will be reloaded.

**Comment by danielperna84** [comment]
Well, I think it should in a way replicate what the CCU UI provides. Currently with only the number of service messages my personal automation is to send a notification if it's greater than `0`. I then log in to my CCU to see what the problem is, fix it, and ideally it goes back to `0`.

It would be more convenient if I wouldn't first have to look at the CCU to know what the problem is. Hence the notification in the HA-UI.

The `STICKY_UNREACH` should be persistent notifications, because AFAIK they have to be manually confirmed. I don't know however if this can also be done via XML-RPC. But the user should be informed about this.

I guess `UNREACH` and `CONFIG_PENDING` are less important. `UNREACH` would be a not-persistent notification, and I guess `CONFIG_PENDING` could be ignored. The latter probably will only come up when the user is using the CCU to do configuration, so he'll be aware of that anyways.

**Comment by SukramJ** [comment]
`STICKY_UNREACH` is used by Bidcos-RF only. So i also added` UNREACH` for HmIP.
I don' think it is possible to send confirmations to CCU, but as soon as the device is back, the persistent notification will be removed in HA. Next step is to add the device name.

**Comment by SukramJ** [comment]
I'am closing this, PNs are released.
